### ISSUE TITLE
SQL инъекции

### ISSUE THREAD

**Issue by GDenisC** [WINnerGMD/PyWIN-Core#1]
пример кода с SQL инъекцией:
```py
@router.post(f'{path}/requestUserAccess.php')
def requestUserAccess(accountID: str = Form()):
    answer = db(f"SELECT * FROM `users` WHERE `id` = {accountID} and `role` > 0;")
```
пример SQL инъекции:
```cu
curl -XPOST -d 'accountID=0;DELETE * FROM `users`;--' db/{path}/requestUserAccess.php
```

**Comment by m41denx** [comment]
@GDenisC Ты чьто, дурачок? Ему теперь все ядро переписывать. Может еще начнешь говорить про то, что неверные запросы будут ядро крашить?

**Comment by ShprotKendal** [comment]
Исправим🐬

**Comment by ShprotKendal** [comment]
> 

![image](https://github.com/WINnerGMD/PyWIN-Core/assets/134456640/d30d7842-7cf9-4e0b-b9a0-91343570178e)
